server: 
  port: 8090
#뷰
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource: #바이바티스
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mulcampingdb.canyejspavcg.us-east-1.rds.amazonaws.com/mulcamping?characterEncoding=UTF-8
    username: admin
    password: mulcam333
  mail:
    host: smtp.gmail.com
    port: 587
    username: mulcamping.com@gmail.com
    password: mulcam33@@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools: # 코드 수정 시 서버 자동 자동실행
    livereload:
      enabled: true
  servlet:  #multipart
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      
mybatis:
  type-aliases-package: com.campus.myapp. #mybatis에서 패키지 생략 할 수 있도록 설정
  mapper-locations: mapper/*Mapper.xml #쿼리문 경로 지정x  
  
